# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /work/halla/solid/tianye/solid_simulation/solid/evgen/evgen_inclusive_e-dflay_dev-4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /work/halla/solid/tianye/solid_simulation/solid/evgen/evgen_inclusive_e-dflay_dev-4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /work/halla/solid/tianye/solid_simulation/solid/evgen/evgen_inclusive_e-dflay_dev-4/CMakeFiles /work/halla/solid/tianye/solid_simulation/solid/evgen/evgen_inclusive_e-dflay_dev-4/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /work/halla/solid/tianye/solid_simulation/solid/evgen/evgen_inclusive_e-dflay_dev-4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named solid_inclusive_e

# Build rule for target.
solid_inclusive_e: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 solid_inclusive_e
.PHONY : solid_inclusive_e

# fast build rule for target.
solid_inclusive_e/fast:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/build
.PHONY : solid_inclusive_e/fast

solid_inclusive_e.o: solid_inclusive_e.C.o
.PHONY : solid_inclusive_e.o

# target to build an object file
solid_inclusive_e.C.o:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/solid_inclusive_e.C.o
.PHONY : solid_inclusive_e.C.o

solid_inclusive_e.i: solid_inclusive_e.C.i
.PHONY : solid_inclusive_e.i

# target to preprocess a source file
solid_inclusive_e.C.i:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/solid_inclusive_e.C.i
.PHONY : solid_inclusive_e.C.i

solid_inclusive_e.s: solid_inclusive_e.C.s
.PHONY : solid_inclusive_e.s

# target to generate assembly for a file
solid_inclusive_e.C.s:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/solid_inclusive_e.C.s
.PHONY : solid_inclusive_e.C.s

src/FileManager.o: src/FileManager.C.o
.PHONY : src/FileManager.o

# target to build an object file
src/FileManager.C.o:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/FileManager.C.o
.PHONY : src/FileManager.C.o

src/FileManager.i: src/FileManager.C.i
.PHONY : src/FileManager.i

# target to preprocess a source file
src/FileManager.C.i:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/FileManager.C.i
.PHONY : src/FileManager.C.i

src/FileManager.s: src/FileManager.C.s
.PHONY : src/FileManager.s

# target to generate assembly for a file
src/FileManager.C.s:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/FileManager.C.s
.PHONY : src/FileManager.C.s

src/Kinematics.o: src/Kinematics.C.o
.PHONY : src/Kinematics.o

# target to build an object file
src/Kinematics.C.o:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/Kinematics.C.o
.PHONY : src/Kinematics.C.o

src/Kinematics.i: src/Kinematics.C.i
.PHONY : src/Kinematics.i

# target to preprocess a source file
src/Kinematics.C.i:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/Kinematics.C.i
.PHONY : src/Kinematics.C.i

src/Kinematics.s: src/Kinematics.C.s
.PHONY : src/Kinematics.s

# target to generate assembly for a file
src/Kinematics.C.s:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/Kinematics.C.s
.PHONY : src/Kinematics.C.s

src/RadiativeCorrections.o: src/RadiativeCorrections.C.o
.PHONY : src/RadiativeCorrections.o

# target to build an object file
src/RadiativeCorrections.C.o:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/RadiativeCorrections.C.o
.PHONY : src/RadiativeCorrections.C.o

src/RadiativeCorrections.i: src/RadiativeCorrections.C.i
.PHONY : src/RadiativeCorrections.i

# target to preprocess a source file
src/RadiativeCorrections.C.i:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/RadiativeCorrections.C.i
.PHONY : src/RadiativeCorrections.C.i

src/RadiativeCorrections.s: src/RadiativeCorrections.C.s
.PHONY : src/RadiativeCorrections.s

# target to generate assembly for a file
src/RadiativeCorrections.C.s:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/RadiativeCorrections.C.s
.PHONY : src/RadiativeCorrections.C.s

src/christy_bosted_inelastic_QE.o: src/christy_bosted_inelastic_QE.C.o
.PHONY : src/christy_bosted_inelastic_QE.o

# target to build an object file
src/christy_bosted_inelastic_QE.C.o:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/christy_bosted_inelastic_QE.C.o
.PHONY : src/christy_bosted_inelastic_QE.C.o

src/christy_bosted_inelastic_QE.i: src/christy_bosted_inelastic_QE.C.i
.PHONY : src/christy_bosted_inelastic_QE.i

# target to preprocess a source file
src/christy_bosted_inelastic_QE.C.i:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/christy_bosted_inelastic_QE.C.i
.PHONY : src/christy_bosted_inelastic_QE.C.i

src/christy_bosted_inelastic_QE.s: src/christy_bosted_inelastic_QE.C.s
.PHONY : src/christy_bosted_inelastic_QE.s

# target to generate assembly for a file
src/christy_bosted_inelastic_QE.C.s:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/christy_bosted_inelastic_QE.C.s
.PHONY : src/christy_bosted_inelastic_QE.C.s

src/eInclusiveCrossSection.o: src/eInclusiveCrossSection.C.o
.PHONY : src/eInclusiveCrossSection.o

# target to build an object file
src/eInclusiveCrossSection.C.o:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/eInclusiveCrossSection.C.o
.PHONY : src/eInclusiveCrossSection.C.o

src/eInclusiveCrossSection.i: src/eInclusiveCrossSection.C.i
.PHONY : src/eInclusiveCrossSection.i

# target to preprocess a source file
src/eInclusiveCrossSection.C.i:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/eInclusiveCrossSection.C.i
.PHONY : src/eInclusiveCrossSection.C.i

src/eInclusiveCrossSection.s: src/eInclusiveCrossSection.C.s
.PHONY : src/eInclusiveCrossSection.s

# target to generate assembly for a file
src/eInclusiveCrossSection.C.s:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/eInclusiveCrossSection.C.s
.PHONY : src/eInclusiveCrossSection.C.s

src/fixed_target_xs.o: src/fixed_target_xs.C.o
.PHONY : src/fixed_target_xs.o

# target to build an object file
src/fixed_target_xs.C.o:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/fixed_target_xs.C.o
.PHONY : src/fixed_target_xs.C.o

src/fixed_target_xs.i: src/fixed_target_xs.C.i
.PHONY : src/fixed_target_xs.i

# target to preprocess a source file
src/fixed_target_xs.C.i:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/fixed_target_xs.C.i
.PHONY : src/fixed_target_xs.C.i

src/fixed_target_xs.s: src/fixed_target_xs.C.s
.PHONY : src/fixed_target_xs.s

# target to generate assembly for a file
src/fixed_target_xs.C.s:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/fixed_target_xs.C.s
.PHONY : src/fixed_target_xs.C.s

src/neutron_DIS.o: src/neutron_DIS.C.o
.PHONY : src/neutron_DIS.o

# target to build an object file
src/neutron_DIS.C.o:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/neutron_DIS.C.o
.PHONY : src/neutron_DIS.C.o

src/neutron_DIS.i: src/neutron_DIS.C.i
.PHONY : src/neutron_DIS.i

# target to preprocess a source file
src/neutron_DIS.C.i:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/neutron_DIS.C.i
.PHONY : src/neutron_DIS.C.i

src/neutron_DIS.s: src/neutron_DIS.C.s
.PHONY : src/neutron_DIS.s

# target to generate assembly for a file
src/neutron_DIS.C.s:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/neutron_DIS.C.s
.PHONY : src/neutron_DIS.C.s

src/proton_DIS.o: src/proton_DIS.C.o
.PHONY : src/proton_DIS.o

# target to build an object file
src/proton_DIS.C.o:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/proton_DIS.C.o
.PHONY : src/proton_DIS.C.o

src/proton_DIS.i: src/proton_DIS.C.i
.PHONY : src/proton_DIS.i

# target to preprocess a source file
src/proton_DIS.C.i:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/proton_DIS.C.i
.PHONY : src/proton_DIS.C.i

src/proton_DIS.s: src/proton_DIS.C.s
.PHONY : src/proton_DIS.s

# target to generate assembly for a file
src/proton_DIS.C.s:
	$(MAKE) -f CMakeFiles/solid_inclusive_e.dir/build.make CMakeFiles/solid_inclusive_e.dir/src/proton_DIS.C.s
.PHONY : src/proton_DIS.C.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... solid_inclusive_e"
	@echo "... solid_inclusive_e.o"
	@echo "... solid_inclusive_e.i"
	@echo "... solid_inclusive_e.s"
	@echo "... src/FileManager.o"
	@echo "... src/FileManager.i"
	@echo "... src/FileManager.s"
	@echo "... src/Kinematics.o"
	@echo "... src/Kinematics.i"
	@echo "... src/Kinematics.s"
	@echo "... src/RadiativeCorrections.o"
	@echo "... src/RadiativeCorrections.i"
	@echo "... src/RadiativeCorrections.s"
	@echo "... src/christy_bosted_inelastic_QE.o"
	@echo "... src/christy_bosted_inelastic_QE.i"
	@echo "... src/christy_bosted_inelastic_QE.s"
	@echo "... src/eInclusiveCrossSection.o"
	@echo "... src/eInclusiveCrossSection.i"
	@echo "... src/eInclusiveCrossSection.s"
	@echo "... src/fixed_target_xs.o"
	@echo "... src/fixed_target_xs.i"
	@echo "... src/fixed_target_xs.s"
	@echo "... src/neutron_DIS.o"
	@echo "... src/neutron_DIS.i"
	@echo "... src/neutron_DIS.s"
	@echo "... src/proton_DIS.o"
	@echo "... src/proton_DIS.i"
	@echo "... src/proton_DIS.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

