#!/bin/bash
#echo "Enter Q2W as: <q2min>-<q2max>__<wmin>-<wmax>; default = 1.4-1.5__1.6-1.8"
#read q2w
#if [ -z $q2w ]
# then
#   echo "no Q2W entered, will use default Q2W range"
#   q2w=1.4-1.5__1.6-1.8
#fi

#echo "Enter descriptor for this Q2W simulation"
read descriptor
if [ -z $descriptor ]
 then
   echo "mandatory desciptor not entered. exiting"
   exit
fi

#echo "Enter number of events to generatei; default = 100K"
#read nevt
#if [ -z $nevt ]
 # then
  #  echo "nevt not entered, will use default nevt[100000]"
   # nevt=50000
#fi

#echo "Enter WALLTIME; default = 1600"
#read walltime
#if [ -z $walltime ]
 # then
  #  echo "walltime not entered, will use default walltime[1600]"
  #  walltime=1600
#fi

#echo "Enter DISKSPACE in MB; default = 2000MB"
#read diskspace
#if [ -z $diskspace ]
 # then
  #  echo "diskspace not entered, will use default diskspace[2000]"
   # diskspace=2000
#fi

identifier=$descriptor
echo $identifier

#q2min=${identifier:5:3}
#q2max=${identifier:9:3}
#wmin=${identifier:14:3}
#wmax=${identifier:18:3}
#echo "[q2min-q2max][wmin-wmax] =""["$q2min"-"$q2max"]""["$wmin"-"$wmax"]"

HERE=/w/halla-scifs17exp/solid/tianye/solid_simulation/solid/evgen/evgen_inclusive_e-dflay_dev-4
echo "starting to submit jobs for $identifier"
SUBDIR=/volatile/halla/solid/tianye/solid_simulation/submit/${identifier}
mkdir ${SUBDIR}
GENEVDIR=/w/halla-scifs17exp/solid/tianye/solid_simulation/solid/evgen/evgen_inclusive_e-dflay_dev-4
MYDIR=/w/halla-scifs17exp/solid/tianye/solid_simulation/solid/evgen/evgen_inclusive_e-dflay_dev-4/input 
OUTDIR=/volatile/halla/solid/tianye/d2n_test
YIELDDIR=${OUTDIR}/ROOT
LUNDDIR=${OUTDIR}/LUND
#YIELDDIR=/volatile/clas/claseg3/atrivedi/data/e1f/simulation_2pi/${identifier}/yield
#mkdir -p ${YIELDDIR}

#modify genev.inp with ranges in identifier
#sed -e s/q2min/$q2min/ -e s/q2max/$q2max/ -e s/wmin/$wmin/ -e s/wmax/$wmax/  -e s/nevt/$nevt/ ${HERE}/genev.inp > ${SUBDIR}/genev.inp

for i in `seq $1 $2`;
do
sed -e s/fileN/$i/ ${HERE}/_generate_lund_He3.sh > ${HERE}/generate_lund_He3_$i.sh
chmod 777 ${HERE}/generate_lund_He3_$i.sh
 JSUBFILE=${SUBDIR}/$i.sub
# echo " "$RANDOM$i > ${SUBDIR}/$i".dat"
 echo "JOBNAME: solid_sim_"$identifier"__"$i      >> $JSUBFILE
 echo "PROJECT: solid"      >> $JSUBFILE
 echo "SINGLE_JOB: true"  >> $JSUBFILE
 echo "OS: centos77"         >> $JSUBFILE
# echo "OS: centos7"         >> $JSUBFILE
echo "TRACK: simulation " >> $JSUBFILE
#echo "TRACK: debug" >> $JSUBFILE
# echo "DISK_SPACE: "$diskspace" MB" >> $JSUBFILE
 #echo "DISK_SPACE: 2000 MB" >> $JSUBFILE 
 echo "DISK_SPACE: 1 GB" >> $JSUBFILE
 echo "MEMORY: 2000 MB" >> $JSUBFILE
# echo "TIME: "$walltime >> $JSUBFILE
 echo "TIME: 1440" >> $JSUBFILE
# echo "TIME: 3000" >> $JSUBFILE
 echo " "                 >> $JSUBFILE
 echo "COMMAND: ./generate_lund_He3_$i.sh"  >> $JSUBFILE
 echo " "                 >> $JSUBFILE
 echo "OTHER_FILES: "$HERE"/generate_lund_He3_$i.sh" >> $JSUBFILE
 # for genev
 echo "OTHER_FILES: "$GENEVDIR"/solid_inclusive_e" >> $JSUBFILE
 echo "OTHER_FILES: "$MYDIR"/parameters_d2n.txt" >> $JSUBFILE
# echo "INPUT_FILES: "${SUBDIR}"/"$i".dat" >> $JSUBFILE
# echo "INPUT_DATA: seed.dat" >> $JSUBFILE
 #for gsim
 #for gpp
 #for ana
# echo "OTHER_FILES: ${GENEVDIR}/nt10maker_mctk_new" >>${JSUBFILE}
 #for analysis2pi
# echo "OTHER_FILES: ${WORKSPACE}/at-ana/analysis2pi" >> ${JSUBFILE}
 echo " "                 >> $JSUBFILE
 #from genev
# echo "OUTPUT_DATA: aao_rad.evt" >> $JSUBFILE
# echo "OUTPUT_TEMPLATE: "${MCTKDIR}"/"$i".mctk" >> $JSUBFILE
 #echo "OUTPUT_DATA: genev123.root" >> $JSUBFILE
# echo "OUTPUT_TEMPLATE: "${MCTKDIR}"/"$i".root" >> $JSUBFILE
 #from gsim
# echo "OUTPUT_DATA: GSIM.OUT" >> ${JSUBFILE}
# echo "OUTPUT_TEMPLATE: ${GSIMDIR}/$i.gsim" >> ${JSUBFILE} 
 #from gpp & ana

# echo "OUTPUT_DATA: GPP_OUT" >> $JSUBFILE

# echo "OUTPUT_TEMPLATE: "${GPPDIR}"/"$i".gpp" >> $JSUBFILE
# from cook
# echo "OUTPUT_DATA: e1e_sim.bos" >> ${JSUBFILE}
# echo "OUTPUT_TEMPLATE: ${COOKDIR}/cookbos_"$i".bos" >> ${JSUBFILE}
# echo "OUTPUT_DATA: e1e_ana.root" >> ${JSUBFILE}
# echo "OUTPUT_TEMPLATE: ${ANADIR}/"$i".root" >> ${JSUBFILE}
# echo "OUTPUT_DATA: generated_testkl.root" >> ${JSUBFILE}
# echo "OUTPUT_TEMPLATE: ${YIELDDIR}/kl_"$i".root" >> ${JSUBFILE}
 #echo "OUTPUT_DATA: output.evio" >> ${JSUBFILE}
#echo "OUTPUT_TEMPLATE: ${YIELDDIR}/output_"$i".evio" >> ${JSUBFILE}
#echo "OUTPUT_DATA:fort_SIDIS_3He_$i.root" >> ${JSUBFILE}
#echo "OUTPUT_TEMPLATE: ${YIELDDIR}/fort_SIDIS_3He_"$i".root" >> ${JSUBFILE}
 echo "OUTPUT_DATA: gen_d2n_$i.root" >> ${JSUBFILE}
 echo "OUTPUT_TEMPLATE: ${YIELDDIR}/gen_d2n_"$i".root" >> ${JSUBFILE}


 jsub $JSUBFILE
 echo "submitted "$identifier"__"$i
done

